### ISSUE TITLE
Error corsi senza candidati

### ISSUE THREAD

**Issue by Raif9** [PoliNetwork/GraduatorieScript#3]
Se in un corso non ci sono stati candidati il sito mostra 404 invece di riportare una pagina che indica l'assenza di candidati per il corso come fa il politecnico

Es: corso di ing civile nella terza graduatoria di seconda fase

Sito polimi http://www.risultati-ammissione.polimi.it/2022_20103_355c_html/2022_20103_sotto_20161.html

Sito polinetwork https://rankings.polinetwork.org/2022_20103_355c_html/2022_20103_sotto_20161.html

**Comment by steven9463912** [comment]
fixed
