### ISSUE TITLE
[BUG] aggiornare link del links.txt

### ISSUE THREAD

**Issue by lorenzocorallo** [PoliNetwork/GraduatorieScript#4]
https://github.com/PoliNetworkOrg/GraduatorieScript/blob/8556d5c45606de770a2a33c7d7e37b48e72ac61e/main.py#L467

Dopo chiusura di https://github.com/PoliNetworkOrg/GraduatorieScriptCSharp/pull/24 cambiare link a 
```
https://raw.githubusercontent.com/PoliNetworkOrg/GraduatorieScriptCSharp/main/data/links.txt
```

**Comment by angeousta** [comment]
closed in https://github.com/PoliNetworkOrg/GraduatorieScript/commit/25f91714c75b3d994ecda62d140b382e7d80ee26
